Repository TeamKeepin/Keepin-iOSArchive, pull requests merged in 2021-07, with the labels that each got.

#7 [feat] Closes #4 머시기 기능을 추가함
  README.md
Labels: pull request, seawater

#8 [feat] 3wns 프린트
  Keepin_iOSArchive/Keepin_iOSArchive.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Keepin_iOSArchive/Keepin_iOSArchive/SamJoon/Temp3/Temp3VC.swift
Labels: 3wns, feat, pull request

#9 pull request
  Keepin_iOSArchive/Keepin_iOSArchive/SilverYoung/Temp2/Temp2VC.swift
  Keepin_iOSArchive/Keepin_iOSArchive/SilverYoung/Temp2/Temp2VC.xib
Labels: pull request, silver
